name: Deploy market-plit.ru

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REGRU_HOST }}
          username: ${{ secrets.REGRU_USER }}
          key: ${{ secrets.REGRU_KEY }}
          script: |

            # For first deploy
            cd /var/www/u1538455/data/www/market-plit.ru/wp-content/themes/site100market-plit
            git clone https://github.com/site100ru/market-plit.ru.git .
            
            # For next deploys
            # cd /var/www/u1538455/data/www/market-plit.ru/wp-content/themes/site100market-plit
            # git pull
